# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deb1714fc382e2d71d974cff4d80497558d34a62b1d50e904567adfa326c4e6e73f058c5cd1c4830edd86ab06a9da6e29c22ee3782ecda726c1551c8fbe06585

test:
  secret_key_base: 6be77cde5d3b7bff590d2f885329605c00f7ce0bf76dff84950db9a9428e909ee5204c1780302352cf69d612ea3d100af52bfb283d9951f40251ef6b743c2a3b

production:
  secret_key_base: hbe77cde5d3b7bfc590g2f485329605c00f5ce0bf76dff84950db9a9428e909ee5204c1780302352cf69d612ea3d100af52bfb283d9951f40251ef6b743c2a3b
